### ISSUE TITLE
Add Torchbearer: A model fitting library for PyTorch

### ISSUE THREAD

**Issue by ethanwharris** [leonoverweel/bibtex-python-package-citations#1]
Hi, nice project!

For PyTorch especially, it may be a good idea to have an additional libraries section.
We maintain a training library for PyTorch called torchbearer:  https://github.com/pytorchbearer/torchbearer

Our bibtex is:
@article{torchbearer2018,
  author = {Ethan Harris and Matthew Painter and Jonathon Hare},
  title = {Torchbearer: A Model Fitting Library for PyTorch},
  journal  = {arXiv preprint arXiv:1809.03363},
  year = {2018}
}

Other libraries you might consider:
ignite: https://github.com/pytorch/ignite
poutyne: https://github.com/GRAAL-Research/poutyne
inferno: https://github.com/inferno-pytorch/inferno

Hope that helps!

**Comment by leonoverweel** [comment]
Added torchbearer in 9f538b9! Can't find good references for the other ones, so I'll leave them out for now.
